language: node_js

notifications:
  email: false

node_js:
  - "12.16.0"

services:
  - postgresql

before_script:
  - cp -a .env.example .env
  - psql -c "CREATE DATABASE your-app-name;" -U postgres
  - psql -c "CREATE USER your-app-name WITH PASSWORD 'password';" -U postgres

install: npm install

jobs:
  include:
    - stage: Tests
      if: |
        branch = develop AND \
        tag IS blank AND \
        commit_message !~ /(no-deploy|wip)/
      script: 
        - npm run lint
        - npm run test:coverage
        - npm run test:coveralls

cache:
  directories:
    - node_modules